project 'ARcheckers.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARcheckers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARcheckers
  pod 'SVProgressHUD'
end

target 'ARcheckersMrDekk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ARcheckersMrDekk
  pod 'SVProgressHUD'
end
